config/routes.rb
Rails.application.routes.draw do
  get 'hello' => 'hello#index'

  # Movies
  resources 'movies'

  # Actors
  resources 'actors'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  belongs_to :movie
  accepts_nested_attributes_for :movie

  validates :name, :age, presence: true

  def self.search(search)
    if search
      self.where 'name LIKE ?', "%#{search}%"
    else
      self.all
    end
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :actors
  #accepts_nested_attributes_for :actors
  # Presence
  validates :name, :year, :price, presence: true
  # Numeric
  validates :year, numericality: true
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }, :numericality => {:greater_than => 0}
  # uniqueness
  validates :name, uniqueness: true

  def self.search(search)
    if search
      self.where "name LIKE ?", "%#{search}%"
    else
      self.all
    end
  end

  def list_actor
    Actor.where "movie_id = ?", self.id
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]
  def index
    @actors = Actor.search(params[:search])
  end

  def show; end

  def new
    @actor = Actor.new
    @actor.build_movie
    @movies = Movie.all
  end

  def create
    @actor = Actor.new(actor_params)
    @movies = Movie.all

    if @actor.save
      flash[:notice] = "Create success!"
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def edit
    @movies = Movie.all
  end

  def update
    if @actor.update(actor_params)
      flash[:notice] = "Update success!"
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  def destroy
    @actor.destroy
    flash[:notice] = 'Delete success!'
    redirect_to action: 'index'
  end

  private

  def set_actor
    @actor = Actor.find(params[:id])
  end

  def actor_params
      params.require(:actor).permit(:name, :age, :movie_id, movie_attributes:[:id, :name, :description, :year, :price])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hello_controller.rb
# HelloController
class HelloController < ApplicationController
  def index
    @name = params[:name].nil? ? 'PAC' : params[:name]
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :destroy, :edit, :update]
  def index
    @movies = Movie.search(params[:search]) 
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      flash[:notice] = "Create success"
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def show
    @actors = @movie.actors
  end

  def destroy
    @movie.destroy

    flash[:notice] = "Deleted success"
    redirect_to action: 'index'
  end

  def edit; end

  def update
    @movie.update movie_params

    flash[:notice] = "Update success"
    redirect_to action: 'index'
  end

  private
  def set_movie
    @movie = Movie.find params[:id]
  end

  def movie_params
    params.require(:movie).permit(:name, :price, :year, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/actors/_form.html.erb
<% if @actor.errors.any? %>
<div class="row">
  <div class="small-12 large-12 column">
  <p><%= pluralize(@actor.errors.count, 'error') %> prohibited this actor from being saved:</p>
  <% @actor.errors.full_messages.each do |message| %>
    <div data-alert class="alert-box alert radius">
      <%= message %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
    </div>
  </div>
</div>
<% end %>

<%= form_for(@actor) do |f| %>
<div class="row"> 
  <div class="small-6 large-6 columns">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="small-6 large-6 columns">
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div>
</div>
<div class="movie-new row">
  <div class="small-6 large-6 columns">
    <%= f.label :movie_id %>
    <%= f.select :movie_id, @movies.map { |m| [m.name, m.id] }, include_blank: true %>
  </div>
  <a href="#" class="toggle-form">New movie</a>
</div>

<div class="movie-new hide">
  <%= f.fields_for :movie do |m| %>
    <div class="row">
      <div class="small-6 large-6 columns">
        <h3>Create Movie</h3>
        <a href class="toggle-form">Existing movie</a>
      </div>
    </div>
    <div class="row">
      <div class="small-6 large-6 columns">
        <%= m.label :name %>
        <%= m.text_field :name %>
      </div>
      <div class="small-6 large-6 columns">
        <%= m.label :description %>
        <%= m.text_field :description %>
      </div>
    </div>
    <div class="row">
      <div class="small-6 large-6 columns">
        <%= m.label :year %>
        <%= m.text_field :year %>
      </div>
      <div class="small-6 large-6 columns">
        <%= m.label :price %>
        <%= m.text_field :price %>
      </div> 
    </div>
    <div class="row">
      <div class="small-6 large-6 columns">
        
      </div>
    </div>

  
  <% end %>
</div>

<div class="row">
  <div class="small-12 large-12 columns">
    <%= f.submit class: "button" %>
  </div>
</div>
<% end %>


<script type="text/javascript">
  $('.toggle-form').click(function() {
    $('.movie-new').toggleClass('hide');  
  });
</script>

app/views/actors/edit.html.erb
<div class="row">
  <div class="small-12 large-12 column">
    <h1>Edit: <%= @actor.name %></h1>
    <p><%= link_to 'Back', actors_path %></p>
  </div>
</div>

<%= render 'form' %>

app/views/actors/index.html.erb
<div class="row">
  <div class="small-12 large-12 column">
    <h1>List of Actors</h1>  
  </div>
</div>

<div class="row">
  <div class="small-12 large-12 column">
    <p>
      <%= link_to 'Add', :new_actor %> |
      <%= link_to 'Movies', movies_path %>
    </p>
  </div>
</div>

<%= form_tag actors_path, :method => 'get' do %>
<div class="row">
 <div class="small-6 large-6 columns">
   <%= text_field_tag :search, params[:search] %>
 </div>
 <div class="small-6 large-6 columns">
   <%= submit_tag "Search", :name => nil, class: 'button tiny' %>
 </div>
</div>
<% end %>

<div class="row">
  <div class="small-12 large-12 column">
  <% if params[:search] %>
    <p><%= link_to 'All', actors_path %></p>
  <% end %>

  <% flash.each do |name, msg| %>
    <div data-alert class="alert-box success radius"><%= msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
    <table>
      <thead>
        <tr>
          <th width="10%">#</th>
          <th width="50%">Name</th>
          <th width="15%">Age</th>
          <th width="25%">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @actors.each do |m| %>
          <tr>
            <td><%= m.id %></td>
            <td><%= m.name %></td>
            <td><%= m.age %></td>
            <td>
              <%= link_to 'Show', actor_path(m.id) %> |
              <%= link_to 'Edit', edit_actor_path(m.id) %> |
              <%= link_to 'Delete', actor_path(m.id), method: :delete %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/actors/new.html.erb
<div class="row">
  <div class="small-12 large-12 column">
    <h1>Add Actor</h1>
    <p><%= link_to 'Back', actors_path %></p>
  </div>
</div>

<%= render 'form' %>

app/views/actors/show.html.erb
<div class="row">
  <div class="small-12 large-12 column">
    <h1><%= @actor.name %></h1>
    <p><%= @actor.age %></p>    
  </div>
</div>

<div class="row">
  <div class="small-12 large-12 column">
    <ul>
      <li><b>Filme:</b> <%= link_to @actor.movie.name, movie_path(@actor.movie.id), method: :get %></li>
    </ul>
    <p><%= link_to 'Back', actors_path %></p>
  </div>
</div>

app/views/hello/index.html.erb
<h1>Hello, <%= @name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/movies/_form.html.erb
<% if @movie.errors.any? %>
<div class="row">
  <div class="small-12 large-12 column">
  <p><%= pluralize(@movie.errors.count, 'error') %> prohibited this movie from being saved:</p>
  <% @movie.errors.full_messages.each do |message| %>
    <div data-alert class="alert-box alert radius">
      <%= message %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
    </div>
  </div>
</div>
<% end %>

<%= form_for(@movie) do |f| %>
<div class="row"> 
  <div class="small-6 large-6 columns">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="small-6 large-6 columns">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
</div>
<div class="row">
  <div class="small-6 large-6 columns">
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>
  <div class="small-6 large-6 columns">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>  
</div>
<!-- <div class="row">
  <div class="small-6 large-6 columns">
   #f.select :actor_id, options_from_collection_for_select(@actors, "id", "name"), include_blank: true %>
  </div>
</div> -->
<div class="row">
  <div class="small-12 large-12 columns">
    <%= f.submit(class: "button") %>
  </div>
</div>
<% end %>

app/views/movies/edit.html.erb
<div class="row">
  <div class="small-12 large-12 column">
    <h1>Edit: <%= @movie.name %></h1>
    <p><%= link_to 'Back', movies_path %></p>
  </div>
</div>

<%= render 'form' %>

app/views/movies/index.html.erb
<div class="row">
  <div class="small-12 large-12 column">
    <h1>List of Movies</h1>
  </div>
</div>

<div class="row">
  <div class="small-12 large-12 column">
    <p>
      <%= link_to 'Add', :new_movie %> |
      <%= link_to 'Actors', actors_path %>
    </p>
  </div>
</div>

<%= form_tag movies_path, :method => 'get' do %>
<div class="row">
 <div class="small-6 large-6 columns">
   <%= text_field_tag :search, params[:search] %>
 </div>
 <div class="small-6 large-6 columns">
   <%= submit_tag "Search", :name => nil, class: 'button tiny' %>
 </div>
</div>
<% end %>

<div class="row">
  <div class="small-12 large-12 column">
  <% if params[:search] %>
    <p><%= link_to 'All', movies_path %></p>
  <% end %>

  <% flash.each do |name, msg| %>
    <div data-alert class="alert-box success radius"><%= msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
    <table>
      <thead>
        <tr>
          <th width="10%">#</th>
          <th width="65%">Name</th>
          <th width="25%">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @movies.each do |m| %>
          <tr>
            <td><%= m.id %></td>
            <td><%= m.name %></td>
            <td>
              <%= link_to 'Show', movie_path(m.id) %> |
              <%= link_to 'Edit', edit_movie_path(m.id) %> |
              <%= link_to 'Delete', movie_path(m.id), method: :delete %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/movies/new.html.erb
<div class="row">
  <div class="small-12 large-12 column">
    <h1>Add Movie</h1>
    <p><%= link_to 'Back', movies_path %></p>
  </div>
</div>

<%= render 'form' %>

app/views/movies/show.html.erb
<div class="row">
  <div class="small-12 large-12 column">
    <h1><%= @movie.name %></h1>
    <p><%= @movie.description %></p>    
  </div>
</div>

<div class="row">
  <div class="small-12 large-12 column">
    <ul>
      <li><b>Year:</b> <%= @movie.year %></li>
      <li><b>Price:</b> <%= @movie.price %></li>
    </ul>
    <p>Actors:</p>
    <ul>
      <% @actors.each do |actor| %>
      <li><%= actor.name %></li>
      <% end %>
    </ul>
    <p><%= link_to 'Back', movies_path %></p>
  </div>
</div>